artifact_alias: latest
batch_size: 32
bbox_interval: -1
bucket: ''
cache: null
cfg: ./models/yolov5s.yaml
cos_lr: false
data: C:/datasets/crack_detector_train/data_train.yaml
device: '0'
entity: null
epochs: 80
evolve: null
exist_ok: false
freeze:
- 0
hyp: data\hyps\hyp.scratch-low.yaml
image_weights: false
imgsz: 640
label_smoothing: 0.0
local_rank: -1
multi_scale: false
name: v14_model_9classes
noautoanchor: false
nosave: false
noval: false
optimizer: SGD
patience: 10
project: runs\train
quad: false
rect: false
resume: false
save_period: -1
single_cls: false
sync_bn: false
upload_dataset: false
weights: yolov5s.pt
workers: 6
save_dir: runs\train\v14_model_9classes
